### ISSUE TITLE
sprite example not working, main readme example not working.

### ISSUE THREAD

**Issue by andykais** [littledivy/deno_sdl2#40]
The sprite example appears to not be fetching some dynamic libs it looking for:
```
~/Code/scratchwork/deno_sdl2/examples/sprite  deno run --unstable --allow-read --allow-net --allow-run --allow-env --allow-write  main.ts
Download target/debug/libdeno_sdl2.dylib
error: Uncaught (in promise) CacheError: /Users/andrew/Code/scratchwork/deno_sdl2/examples/sprite/target/debug/libdeno_sdl2.dylib is not valid.
    throw new CacheError(`${path} is not valid.`);
          ^
    at protocolFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:12:11)
    at async fetchFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:41:14)
    at async FileWrapper.fetch (https://deno.land/x/cache@0.2.13/file.ts:95:18)
    at async FileWrapper.get (https://deno.land/x/cache@0.2.13/file.ts:113:12)
    at async cache (https://deno.land/x/cache@0.2.13/cache.ts:67:10)
    at async Wrapper.cache (https://deno.land/x/cache@0.2.13/cache.ts:21:12)
    at async Module.prepare (https://deno.land/x/plug@0.4.0/plug.ts:75:16)
    at async file:///Users/andrew/Code/scratchwork/deno_sdl2/bindings/bindings.ts:11:14
```
it also is missing a few permissions in the readme (`--allow-env --allow-write`)

the main readme example has some incorrect type errors:
```
~/Code/scratchwork/deno_sdl2  deno run --unstable sample.ts
Check file:///Users/andrew/Code/scratchwork/deno_sdl2/sample.ts
error: TS2345 [ERROR]: Argument of type '{ title: string; width: number; height: number; }' is not assignable to parameter of type 'WindowOptions'.
  Type '{ title: string; width: number; height: number; }' is missing the following properties from type 'WindowOptions': flags, centered, fullscreen, hidden, and 3 more.
const canvas = new Canvas({ title: "Hello, Deno!", width: 800, height: 400 });
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/andrew/Code/scratchwork/deno_sdl2/sample.ts:3:27
```
it is also missing the `--unstable` flag

**Comment by littledivy** [comment]
Fixed the library loading issue by upgrading `deno_bindgen`. Added build instructions to the README for the same.

The sprite example has the `--unstable` flag. Updated other permissions.

**Comment by andykais** [comment]
still not quite successful. I followed the build from source instructions (I assume public libraries are going to compile & provide binaries themselves) but `deno_bindgen -- --features "use_vcpkg"` gives this error:
```
error: Package `deno_sdl2 v0.2.0 (/Users/andrew/Code/scratchwork/deno_sdl2)` does not have the feature `use_vcpkg`
```
I made sure I pulled from main and installed the latest deno_bindgen before running this.

these commands all succeeded:
```bash
deno install -Afq -n deno_bindgen https://raw.githubusercontent.com/littledivy/deno_bindgen/main/cli.ts
cargo install cargo-vcpkg
cargo vcpkg -v build
```

**Comment by andykais** [comment]
I am using rust 1.58. Is that possibly the issue?
`cargo --version`
```
cargo 1.58.0-nightly (94ca096af 2021-10-29)
```

**Comment by littledivy** [comment]
@andykais I think something changed recently with Cargo features naming. `_` in feature names do not map to `-`'s anymore. 
This should work: `deno_bindgen -- --features "use-vcpkg"`

**Comment by andykais** [comment]
Ooo! Its working
<img width="408" alt="Screen Shot 2021-12-09 at 3 11 38 PM" src="https://user-images.githubusercontent.com/6627147/145468662-56d6514f-9727-482b-a8dd-8ca7d6c63538.png">

Thanks @littledivy. It might be worth shoring up the readme with that change. Also the examples readme isnt quite accurate either (e.g. `deno run --unstable -A  main.ts` from the `examples/sprite` folder doesnt work, but `deno run --unstable -A examples/sprite/main.ts` from the main folder does work).

Feel free to close this issue since my problem is solved, but it just might be worth fixing the readme before closing it

**Comment by adamsmasher** [comment]
Looks like this broke as of Deno 1.17.0, where "buffer" is no longer a valid `ForeignFunction` parameter (see https://github.com/denoland/deno/commit/ee49cce726c27cdcb372b9dba7f2deab840d9e6b#diff-50535d25bde221d79f9204917ea7cd78b3ceb55283838a89aa8e04a3a29d0b7a)

```
error: TS2322 [ERROR]: Type '"buffer"' is not assignable to type 'NativeType'.
    parameters: ["buffer", "usize"],
                 ~~~~~~~~
    at https://deno.land/x/sdl2@0.2-alpha.1/bindings/bindings.ts:13:18

TS2322 [ERROR]: Type '"buffer"' is not assignable to type 'NativeType'.
    parameters: ["buffer", "usize", "buffer", "usize"],
                 ~~~~~~~~
    at https://deno.land/x/sdl2@0.2-alpha.1/bindings/bindings.ts:18:18

TS2322 [ERROR]: Type '"buffer"' is not assignable to type 'NativeType'.
    parameters: ["buffer", "usize", "buffer", "usize"],
                                    ~~~~~~~~
    at https://deno.land/x/sdl2@0.2-alpha.1/bindings/bindings.ts:18:37

TS2322 [ERROR]: Type '"buffer"' is not assignable to type 'NativeType'.
    parameters: ["buffer", "usize"],
                 ~~~~~~~~
    at https://deno.land/x/sdl2@0.2-alpha.1/bindings/bindings.ts:23:18
```

**Comment by littledivy** [comment]
Fixed in 0.5.1
